export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  SUPPORT_AGENT = 'SUPPORT_AGENT',
  VIEWER = 'VIEWER',
}

export enum DeviceStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  PAIRING = 'PAIRING',
  PAIRED = 'PAIRED',
  UNPAIRED = 'UNPAIRED',
  SUSPENDED = 'SUSPENDED',
}

export enum PairingStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}

export enum CommandType {
  GET_DEVICE_INFO = 'GET_DEVICE_INFO',
  GET_BATTERY_STATUS = 'GET_BATTERY_STATUS',
  GET_NETWORK_STATUS = 'GET_NETWORK_STATUS',
  PING = 'PING',
  REQUEST_DIAGNOSTIC = 'REQUEST_DIAGNOSTIC',
}

export enum CommandStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  TIMEOUT = 'TIMEOUT',
}

export enum VulnerabilitySeverity {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  INFORMATIONAL = 'INFORMATIONAL',
}

export enum VulnerabilityStatus {
  OPEN = 'OPEN',
  RESOLVED = 'RESOLVED',
  ACCEPTED_RISK = 'ACCEPTED_RISK',
  FALSE_POSITIVE = 'FALSE_POSITIVE',
}

export enum SecurityEventType {
  FAILED_LOGIN_THRESHOLD = 'FAILED_LOGIN_THRESHOLD',
  PAIRING_REPLAY_ATTEMPT = 'PAIRING_REPLAY_ATTEMPT',
  INVALID_DEVICE_SIGNATURE = 'INVALID_DEVICE_SIGNATURE',
  UNAUTHORIZED_RESOURCE_ACCESS = 'UNAUTHORIZED_RESOURCE_ACCESS',
  SUSPICIOUS_FILE_OPERATION = 'SUSPICIOUS_FILE_OPERATION',
  BRUTE_FORCE_DETECTED = 'BRUTE_FORCE_DETECTED',
  SESSION_HIJACK_ATTEMPT = 'SESSION_HIJACK_ATTEMPT',
}

export enum AuditAction {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_REGISTER = 'USER_REGISTER',
  USER_MFA_ENABLE = 'USER_MFA_ENABLE',
  USER_MFA_DISABLE = 'USER_MFA_DISABLE',
  USER_PASSWORD_CHANGE = 'USER_PASSWORD_CHANGE',
  DEVICE_PAIR = 'DEVICE_PAIR',
  DEVICE_UNPAIR = 'DEVICE_UNPAIR',
  DEVICE_COMMAND_SENT = 'DEVICE_COMMAND_SENT',
  SUPPORT_SESSION_START = 'SUPPORT_SESSION_START',
  SUPPORT_SESSION_END = 'SUPPORT_SESSION_END',
  VULNERABILITY_CREATE = 'VULNERABILITY_CREATE',
  VULNERABILITY_UPDATE = 'VULNERABILITY_UPDATE',
  REPORT_GENERATE = 'REPORT_GENERATE',
  FILE_UPLOAD = 'FILE_UPLOAD',
  FILE_DELETE = 'FILE_DELETE',
  SETTINGS_UPDATE = 'SETTINGS_UPDATE',
}

export enum SupportSessionStatus {
  REQUESTED = 'REQUESTED',
  CONSENT_PENDING = 'CONSENT_PENDING',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  TERMINATED = 'TERMINATED',
  EXPIRED = 'EXPIRED',
}

export enum ScreenShareStatus {
  INACTIVE = 'INACTIVE',
  AWAITING_CONSENT = 'AWAITING_CONSENT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  STOPPED = 'STOPPED',
}

export enum LabTargetType {
  ANDROID_DEVICE = 'ANDROID_DEVICE',
  VULNERABLE_API = 'VULNERABLE_API',
  NETWORK_SERVICE = 'NETWORK_SERVICE',
}

export enum ScanType {
  DEVICE_POSTURE = 'DEVICE_POSTURE',
  APK_STATIC_ANALYSIS = 'APK_STATIC_ANALYSIS',
  NETWORK_SCAN = 'NETWORK_SCAN',
  API_SECURITY = 'API_SECURITY',
  MANIFEST_AUDIT = 'MANIFEST_AUDIT',
}
